### ISSUE TITLE
AssertionError: Configuration file need to be specified.

### ISSUE THREAD

**Issue by aswa123** [duwt/OrienMask#11]
Hello,
When I try to run the code I got this error.

Traceback (most recent call last):
  File "/home/swap/miniconda3/envs/orienmask/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-c3ce1dfc6ce0>", line 1, in <module>
    runfile('/home/swap/Downloads/OrienMask-master/train.py', wdir='/home/swap/Downloads/OrienMask-master')
  File "/home/swap/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/202.7660.27/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/swap/.local/share/JetBrains/Toolbox/apps/PyCharm-C/ch-0/202.7660.27/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/swap/Downloads/OrienMask-master/train.py", line 33, in <module>
    raise AssertionError("Configuration file need to be specified.")
AssertionError: Configuration file need to be specified.

**Comment by aswa123** [comment]
I try to Debug but still same.
I am using single GPU.

**Comment by duwt** [comment]
It's clear that the configuration file has not been specified. Please check the training command.
