### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by aswa123** [duwt/OrienMask#9]
Hello,
When I try to run this "python setup.py develop" this command i got this error.
Can you please help me with this.

**Comment by duwt** [comment]
Could you provide more details about the error?

**Comment by aswa123** [comment]
(orienmask) swap@pop-os:~/Downloads/OrienMask-master$ python setup.py develop
/home/swap/miniconda3/envs/orienmask/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448224956/work/c10/cuda/CUDAFunctions.cpp:115.)
  return torch._C._cuda_getDeviceCount() > 0
No CUDA runtime is found, using CUDA_HOME='/usr/lib/cuda'
running develop
running egg_info
writing OrienMaskExtension.egg-info/PKG-INFO
writing dependency_links to OrienMaskExtension.egg-info/dependency_links.txt
writing top-level names to OrienMaskExtension.egg-info/top_level.txt
reading manifest file 'OrienMaskExtension.egg-info/SOURCES.txt'
writing manifest file 'OrienMaskExtension.egg-info/SOURCES.txt'
running build_ext
building 'eval.nms_cpu' extension
Emitting ninja build file /home/swap/Downloads/OrienMask-master/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
g++ -pthread -shared -B /home/swap/miniconda3/envs/orienmask/compiler_compat -L/home/swap/miniconda3/envs/orienmask/lib -Wl,-rpath=/home/swap/miniconda3/envs/orienmask/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/swap/Downloads/OrienMask-master/build/temp.linux-x86_64-3.7/eval/src/nms_cpu.o -L/home/swap/miniconda3/envs/orienmask/lib/python3.7/site-packages/torch/lib -L/usr/lib/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.7/eval/nms_cpu.cpython-37m-x86_64-linux-gnu.so
building 'eval.nms_cuda' extension
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    cmdclass={'build_ext': BuildExtension}
  File "/home/swap/miniconda3/envs/orienmask/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/swap/miniconda3/envs/orienmask/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/swap/miniconda3/envs/orienmask/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/swap/miniconda3/envs/orienmask/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/swap/miniconda3/envs/orienmask/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/swap/miniconda3/envs/orienmask/lib/python3.7/site-packages/setuptools/command/develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "/home/swap/miniconda3/envs/orienmask/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/swap/miniconda3/envs/orienmask/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/swap/miniconda3/envs/orienmask/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/swap/miniconda3/envs/orienmask/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/swap/miniconda3/envs/orienmask/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/swap/miniconda3/envs/orienmask/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
    build_ext.build_extensions(self)
  File "/home/swap/miniconda3/envs/orienmask/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/swap/miniconda3/envs/orienmask/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/swap/miniconda3/envs/orienmask/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/swap/miniconda3/envs/orienmask/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/swap/miniconda3/envs/orienmask/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/swap/miniconda3/envs/orienmask/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 525, in unix_wrap_ninja_compile
    cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
  File "/home/swap/miniconda3/envs/orienmask/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 424, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/home/swap/miniconda3/envs/orienmask/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1562, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range

**Comment by aswa123** [comment]
pip install -r requirements
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements'

**Comment by duwt** [comment]
> pip install -r requirements
> ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements'

I will fix the bug later. Run `pip install -r requirements.txt` instead.

**Comment by duwt** [comment]
It seems something wrong with cuda. Maybe you have to check if the gpu version of pytorch has been correctly installed.

**Comment by aswa123** [comment]
cuda version is 10.2
and pytorch version is 1.9.0

**Comment by duwt** [comment]
I have no idea about that. Maybe you can test with `torch.cuda.is_available()` or install pytorch-1.6.0.

**Comment by aswa123** [comment]
Okay.
Thank you so much for your quick reply.
